Repository MangoFVTT/fvtt-ready-set-roll-5e, pull requests merged in 2022-09, with the labels that each got.

#4 Fix incorrect file path
  module.json
Labels: bug

#5 Merge develop for Release 1.0.1
  module.json
Labels: release

#8 Code Cleanup
  src/module/config.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/log.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
Labels: documentation

#10 hotfix/negative-mod-values
  src/utils/item.js
Labels: bug

#12 hotfix/item-ability-checks
  src/utils/item.js
Labels: bug

#13 release/1.0.2
  src/module/config.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/log.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
Labels: release

#14 hotfix/versatile-option-is-ignored
  src/utils/item.js
Labels: bug

#16 bugfix/consume-uses-not-in-config
  src/utils/sheet.js
Labels: bug

#19 bugfix/other-formula-not-rolling
  src/utils/item.js
  src/utils/sheet.js
  templates/rsr-item-options.html
Labels: bug

#20 bugfix/chat-card-toggle-content
  src/module/templates.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  templates/rsr-blank.html
Labels: bug

#21 release/1.0.3
  src/module/templates.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/sheet.js
  templates/rsr-blank.html
  templates/rsr-item-options.html
Labels: release

#22 feature/damage-context-fields
  README.md
  lang/en.json
  src/module/config.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/sheet.js
Labels: enhancement

#23 feature/dice-roll-sounds
  lang/en.json
  src/module/quickroll.js
  src/utils/core.js
  src/utils/settings.js
Labels: enhancement

#24 release/1.1.0
  README.md
  lang/en.json
  src/module/config.js
  src/module/quickroll.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
Labels: release

#26 bugfix/d20-rolls-not-in-chat-message
  src/module/quickroll.js
  src/utils/patching.js
Labels: bug

#28 feature/always-on-dual-rolls
  lang/en.json
  src/utils/item.js
  src/utils/roll.js
  src/utils/settings.js
Labels: enhancement

#29 bugfix/destroyed-items-save-error
  src/module/quickroll.js
Labels: bug

#30 internal/log-utility-cleanup
  src/utils/core.js
  src/utils/log.js
Labels: enhancement

#36 feature/damage-overlay-buttons
  css/ready-set-roll.css
  icons/overlay-damage-double.svg
  icons/overlay-damage-full.svg
  icons/overlay-damage-half.svg
  icons/overlay-damage-quarter.svg
  icons/overlay-healing-temp.svg
  icons/overlay-healing.svg
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/chat.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/log.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  templates/rsr-overlay-damage.html
Labels: enhancement

#38 bugfix/uncrecognized-crits-dual-rolls
  src/utils/item.js
Labels: bug

#42 feature/retroactive-overlay-buttons
  lang/en.json
  src/module/config.js
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/chat.js
  src/utils/core.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  templates/rsr-multiroll.html
  templates/rsr-overlay-damage.html
  templates/rsr-overlay-multiroll.html
Labels: enhancement

#43 release/1.3.0
  README.md
  css/ready-set-roll.css
  icons/overlay-damage-double.svg
  icons/overlay-damage-full.svg
  icons/overlay-damage-half.svg
  icons/overlay-damage-quarter.svg
  icons/overlay-healing-temp.svg
  icons/overlay-healing.svg
  lang/en.json
  src/module/config.js
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/chat.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/log.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  templates/rsr-multiroll.html
  templates/rsr-overlay-damage.html
  templates/rsr-overlay-multiroll.html
Labels: release

#46 feature/pt-BR-localization
  lang/pt-BR.json
Labels: enhancement

#47 bugfix/retroactive-crit-bugs
  src/module/quickroll.js
  src/utils/roll.js
Labels: bug

#48 feature/dae-compatibility
  src/utils/item.js
Labels: enhancement

#49 release/1.3.1
  README.md
  lang/pt-BR.json
  src/module/quickroll.js
  src/utils/item.js
  src/utils/roll.js
Labels: release

#50 bugfix/flat-damage-error
  src/module/quickroll.js
Labels: bug

#51 feature/babonus-compatibility
  src/module/quickroll.js
  src/utils/hooks.js
Labels: enhancement

#52 release-1.3.2
  README.md
  src/module/quickroll.js
  src/utils/hooks.js
Labels: release

#53 hotfix/babonus-save-bonus-error
  src/module/quickroll.js
Labels: bug

#54 Develop
  src/module/quickroll.js
Labels: release

#57 bugfix/customizing-crit-damage
  src/module/quickroll.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
Labels: bug

#58 release/1.3.4
  src/module/quickroll.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
Labels: release

#61 Add options for applying damage
  lang/en.json
  src/module/quickcard.js
  src/utils/settings.js
Labels: enhancement

#62 release/1.3.5
  lang/en.json
  src/module/quickcard.js
  src/utils/settings.js
Labels: release

#65 bugfix/retroactive-3d-dice
  src/module/quickroll.js
  src/utils/core.js
  src/utils/roll.js
Labels: bug

#67 feature/manual-damage-button
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/chat.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  templates/rsr-damage-button.html
  templates/rsr-save-button.html
Labels: enhancement

#72 bugfix/argon-synthetic-items
  src/utils/roll.js
Labels: bug

#73 release/1.3.6
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/chat.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  templates/rsr-damage-button.html
  templates/rsr-save-button.html
Labels: release

#75 feature/client-side-roll-options
  src/utils/settings.js
Labels: enhancement

#76 Translations update from Foundry Hub - Weblate
  lang/pt-BR.json
Labels: enhancement

#80 hotfix/ensure-flags-on-npc-items
  src/utils/item.js
Labels: bug

#81 hotfix/ensure-click-event
  src/utils/patching.js
Labels: bug

#82 hotfix/fix-consumable-duplication
  src/module/quickroll.js
Labels: bug

#83 release/1.3.8
  lang/pt-BR.json
  src/module/quickroll.js
  src/utils/item.js
  src/utils/patching.js
Labels: release

#85 release/1.3.9
  module.json
Labels: release
