Repository MangoFVTT/fvtt-ready-set-roll-5e, pull requests merged in 2023-06, with the labels that each got.

#198 feature/quick-deathsave
  src/module/config.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
Labels: feature

#199 feature/versatile-ammunition
  src/module/config.js
  src/utils/item.js
Labels: feature

#201 feature/situational-bonuses
  lang/en.json
  src/module/config.js
  src/module/templates.js
  src/utils/dialog.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
  templates/rsr-dialog-bonus.html
Labels: feature

#203 bugfix/situ-bonus-bugs
  src/utils/item.js
  src/utils/roll.js
Labels: bug

#202 release/2.0.0
  README.md
  lang/en.json
  module.json
  src/module/config.js
  src/module/templates.js
  src/utils/core.js
  src/utils/dialog.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
  templates/rsr-dialog-bonus.html
Labels: release

#204 feature/dice-reroll
  css/ready-set-roll.css
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
  templates/rsr-multiroll.html
Labels: feature

#205 localisation/pt-BR
  lang/pt-BR.json
Labels: localisation

#206 feature/expanded-apply-options
  lang/en.json
  src/module/quickcard.js
  src/utils/settings.js
Labels: feature

#210 bugfix/refresh-flags-on-ammunition
  src/utils/item.js
Labels: bug

#212 feature/expanded-manual-damage-options
  lang/en.json
  src/module/quickcard.js
  src/utils/item.js
  src/utils/roll.js
  src/utils/settings.js
Labels: feature

#215 Implemented Damage Calculation
  src/module/quickcard.js
Labels: feature

#217 feature/auto-damage-reductions
  lang/en.json
  src/module/quickcard.js
  src/utils/core.js
  src/utils/settings.js
Labels: feature
