Repository MangoFVTT/fvtt-ready-set-roll-5e, pull requests merged in 2023-01, with the labels that each got.

#125 Store fields in flags as JSON strings (Fixes #121)
  src/module/quickroll.js
Labels: bug

#126 feature/quick-roll-descriptions-default
  lang/en.json
  src/module/config.js
  src/utils/settings.js
Labels: enhancement

#127 bugfix/spell-consume-config-fix
  src/utils/item.js
Labels: bug

#128 bugfix/crit-threshold-colouring
  css/ready-set-roll.css
  src/utils/render.js
Labels: bug

#129 release/1.3.14
  css/ready-set-roll.css
  lang/en.json
  src/module/config.js
  src/module/quickroll.js
  src/utils/item.js
  src/utils/render.js
  src/utils/settings.js
Labels: release

#130 feature/hide-save-dc
  lang/en.json
  src/module/quickcard.js
  src/utils/item.js
  src/utils/settings.js
Labels: enhancement

#135 bugfix/auto-height-on-sheet
  src/utils/sheet.js
Labels: bug

#136 feature/passthrough-roll-mode-for-actor-rolls
  src/utils/patching.js
  src/utils/roll.js
Labels: enhancement

#141 feature/macro-support
  lang/en.json
  lang/pt-BR.json
  src/module/quickroll.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/macro.js
  src/utils/patching.js
  src/utils/render.js
  src/utils/roll.js
  templates/rsr-header.html
Labels: enhancement

#142 feature/query-support
  src/utils/hooks.js
  src/utils/query.js
Labels: enhancement

#143 release/1.4.0
  README.md
  lang/en.json
  lang/pt-BR.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/macro.js
  src/utils/patching.js
  src/utils/query.js
  src/utils/render.js
  src/utils/roll.js
  src/utils/settings.js
  src/utils/sheet.js
  templates/rsr-header.html
Labels: release

#145 bugfix/apply-ammo-traits
  src/utils/item.js
  src/utils/roll.js
Labels: bug

#146 bugfix/use-versatile-part-length
  src/utils/item.js
Labels: bug

#147 release/1.4.1
  src/utils/item.js
  src/utils/roll.js
Labels: release
