Repository MangoFVTT/fvtt-ready-set-roll-5e, pull requests merged in 2023-05, with the labels that each got.

#185 bugfix/custom-ability-skills-title
  src/utils/roll.js
Labels: bug

#186 bugfix/custom-item-config
  src/utils/hooks.js
  src/utils/roll.js
Labels: bug

#187 bugfix/wildcard-token-images
  src/utils/core.js
Labels: bug

#188 release/1.5.2
  src/utils/core.js
  src/utils/hooks.js
  src/utils/item.js
  src/utils/roll.js
Labels: release

#189 Feature/quick roll repeat button
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/core.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  templates/rsr-overlay-header.html
Labels: feature

#192 bugfix/dnd220-new-abilities-object-structure
  src/utils/roll.js
Labels: bug

#193 release/1.5.3
  lang/en.json
  src/module/quickcard.js
  src/module/quickroll.js
  src/module/templates.js
  src/utils/core.js
  src/utils/item.js
  src/utils/render.js
  src/utils/roll.js
  templates/rsr-overlay-header.html
Labels: release

#195 Fix issue with repeating upcasts
  src/module/quickroll.js
  src/utils/roll.js
Labels: bug

#196 release/1.5.4
  src/module/quickroll.js
  src/utils/roll.js
Labels: release
